#pragma once

#include <Windows.h>

#define IO_GET_CLIENTADDRESS CTL_CODE(FILE_DEVICE_UNKNOWN, 0x606, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)

#define IO_READ_REQUEST CTL_CODE(FILE_DEVICE_UNKNOWN, 0x607, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)

#define IO_WRITE_REQUEST CTL_CODE(FILE_DEVICE_UNKNOWN, 0x608, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)

#define IO_REQUEST_PROCESSID CTL_CODE(FILE_DEVICE_UNKNOWN, 0x609, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)

#define IO_QUERY_REQUEST CTL_CODE(FILE_DEVICE_UNKNOWN, 0x600, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)


typedef struct _KERNEL_READ_REQUEST {

	ULONG ProcessId;
	ULONGLONG Address;
	PVOID pBuff;
	ULONGLONG Size;

} KERNEL_READ_REQUEST, * PKERNEL_READ_REQUEST;

typedef struct _KERNEL_WRITE_REQUEST {

	ULONG ProcessId;
	ULONGLONG Address;
	PVOID pBuff;
	ULONGLONG Size;

} KERNEL_WRITE_REQUEST, * PKERNEL_WRITE_REQUEST;

typedef struct _KERNEL_COPY_REQUEST {

	ULONG ProcessId;
	ULONGLONG Address;
	PVOID pBuff;
	ULONGLONG Size;
	//UCHAR* pattern;
	//char* mask;

} KERNEL_COPY_REQUEST, * PKERNEL_COPY_REQUEST;

typedef struct ClientInfo
{
	ULONGLONG BaseAddress;
	ULONGLONG Size;

}ClientInfo, * pClientInfo;
